### ISSUE TITLE
数据格式问题

### ISSUE THREAD

**Issue by kfcx** [zhcong/traTV#1]
首先我对你的这个项目很感兴趣，做的挺不错的
由于我访问https://iptv.tsinghua.edu.cn/epg/todayepg.json该链接会跳转到登录界面，而我不能够注册该网站账号，
麻烦可以提供一下
# https://iptv.tsinghua.edu.cn/channels.json
# https://iptv.tsinghua.edu.cn/epg/todayepg.json 节目表
这两个链接的数据参数吗？
非常感谢！

**Comment by zhcong** [comment]
这个视频源已经不再维护。之前是在教育网下使用的，现在已没有环境测试

**Comment by kfcx** [comment]
> 这个视频源已经不再维护。之前是在教育网下使用的，现在已没有环境测试

好吧，那打扰了。
